language: node_js
node_js:
- '8'
before_install:
- openssl aes-256-cbc -K $encrypted_590739c235a5_key -iv $encrypted_590739c235a5_iv
  -in .travis/deploy_key.enc -out .travis/deploy_key -d
after_success:
- eval "$(ssh-agent)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- ssh-keyscan apps.espe.tech >> ~/.ssh/known_hosts
- git remote add deploy dokku@apps.espe.tech:guestbook
- git config --global push.default simple
- git push deploy master